sonar.projectKey=lumina-shopping
sonar.projectName=Lumina Shopping
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.sources=FE/src,FE/api,BE/src,api

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/UI mock/**,**/supabase/**,**/*.sql,**/*.html
